name: Check Semver

on:
  pull_request:
    branches:
      - main

jobs:
  check-semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: obi1kenobi/cargo-semver-checks-action@v2
